In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))
data

array([[34,  7],
       [71, 94],
       [97, 73],
       [87, 22],
       [ 2, 46],
       [40, 28],
       [13, 60],
       [45, 14],
       [84, 41],
       [ 2, 11]])

In [4]:
scaler_model = MinMaxScaler()
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [5]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [6]:
scaler_model.transform(data)

array([[0.33684211, 0.        ],
       [0.72631579, 1.        ],
       [1.        , 0.75862069],
       [0.89473684, 0.17241379],
       [0.        , 0.44827586],
       [0.4       , 0.24137931],
       [0.11578947, 0.6091954 ],
       [0.45263158, 0.08045977],
       [0.86315789, 0.3908046 ],
       [0.        , 0.04597701]])

In [7]:
## do it at once
scaler_model.fit_transform(data)

array([[0.33684211, 0.        ],
       [0.72631579, 1.        ],
       [1.        , 0.75862069],
       [0.89473684, 0.17241379],
       [0.        , 0.44827586],
       [0.4       , 0.24137931],
       [0.11578947, 0.6091954 ],
       [0.45263158, 0.08045977],
       [0.86315789, 0.3908046 ],
       [0.        , 0.04597701]])

In [8]:
## train test split

In [18]:
import pandas as pd

my_data = np.random.randint(0,101,(50,4))

df = pd.DataFrame(data=my_data,columns = ['f1','f2','f3','label'])
df

     f1  f2   f3  label
0    52  88    4     24
1    44  92   16     78
2    42  44   59     76
3    60  72   57     26
4    58  17   98     38
5    59  86   23     66
6    82   7   46     65
7    87  91   12     96
8    14  56   14     55
9    18  68   39     55
10    7  12   38     95
11   13  95   13     26
12    7  55   99     96
13   66  85   43     97
14   39  61   56     76
15   42  13   30     14
16   51   6   50     56
17   26  43   41      1
18   36  83   24     76
19    2  28   47     99
20   28  73   88     85
21   93  17   17     57
22   37  70   92     82
23   82  16   80     39
24   88  26   35     45
25   42  73   20     30
26   62  19   89     60
27   81  42   73     50
28   47  30   83     41
29  100   0   60     25
30   55  38  100     15
31   82  60    8     79
32   30  25   96     30
33   28  55   62     62
34   27  32   88     79
35   22  90    6     59
36   66  26   40     27
37   16  51   53     58
38   80  78    4     14
39   52  26   50     11
40   67  25   12     89
41   58  19   37     52
42   48  62   40     58
43   13  88    3     89
44    3  63   38     78
45   86  38   98     89
46   77  74   20     54
47   58  53   86     22
48   14  47   41     36
49   25  63   54      1

In [19]:
X = df[['f1','f2','f3']]
y = df['label']

In [20]:
y

0     24
1     78
2     76
3     26
4     38
5     66
6     65
7     96
8     55
9     55
10    95
11    26
12    96
13    97
14    76
15    14
16    56
17     1
18    76
19    99
20    85
21    57
22    82
23    39
24    45
25    30
26    60
27    50
28    41
29    25
30    15
31    79
32    30
33    62
34    79
35    59
36    27
37    58
38    14
39    11
40    89
41    52
42    58
43    89
44    78
45    89
46    54
47    22
48    36
49     1
Name: label, dtype: int32

In [24]:
from sklearn.model_selection import train_test_split

## random_state is like random_seed()
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [25]:
X_train.shape

(35, 3)

In [26]:
X_test.shape

(15, 3)